Payment desevolvimento da criação de uma cobrança e do save
Mikael-Asaas/Asaas pull request #12
Opened 2022-05-18 15:05 UTC by Mikael-Asaas

### Impacto
Desenvolvimento da criação de uma nova cobrança junto com o desenvolvimento da estrutura do save.

### PR Predecessora

### Link da tarefa no JIRA / Trello
https://asaasdev.atlassian.net/browse/STAGS-18?atlOrigin=eyJpIjoiYWQzNDM0NzhjNWQxNDAxNWExMmI2ZmVmZDJkMGRmNjgiLCJwIjoiaiJ9

### Prints do desenvolvimento
![Paymente Criação de uma nova cobrança](https://user-images.githubusercontent.com/101341760/169074445-2fd7c8c1-baa2-4d52-8b50-0b84f4024162.gif)

2022-05-19 13:06 UTC, Yuri-Ferrari requested changes

2022-05-19 13:06 UTC, Yuri-Ferrari commented on grails-app/controllers/com/desafio/domain/PaymentController.groovy
> +        PagedResultList paymentList =  Payment.createCriteria().list(max: getLimitPage(), offset: getCurrentPage()){
```suggestion
        PagedResultList paymentList =  Payment.createCriteria().list(max: getLimitPage(), offset: getCurrentPage()) {
```

2022-05-19 13:06 UTC, Yuri-Ferrari commented on grails-app/controllers/com/desafio/domain/PaymentController.groovy
> +            like("customer", Customer.get(customerId))
Por questões de performance vale utilizar `eq` pra quando acontece comparações diretas do que `like`, replicar em outros lugares

2022-05-19 13:06 UTC, Yuri-Ferrari commented on src/main/groovy/com/desafio/enums/PaymentMethod.groovy
> +    PIX
É preferível utilizar nomes em inglês para código e utilizar o message.properties para mostrar a tradução para os clientes se necessário.

2022-05-23 16:36 UTC, Yuri-Ferrari requested changes

2022-05-23 16:36 UTC, Yuri-Ferrari commented on grails-app/controllers/com/desafio/domain/PaymentController.groovy
> +        [payerList: payerList, totalCount: Payer.count()]
Esse array está 'solto'

2022-05-24 14:56 UTC, Yuri-Ferrari requested changes

2022-05-24 14:56 UTC, Yuri-Ferrari commented on grails-app/controllers/com/desafio/domain/PaymentController.groovy
> +        return [customerId: customerId, payerList: payerList, totalCount: Payer.count()]
O totalCount é usado?

2022-05-26 11:20 UTC, bmorais21 requested changes

2022-05-26 11:20 UTC, bmorais21 commented on grails-app/controllers/com/desafio/domain/PayerController.groovy
>          PagedResultList payerList =  Payer.createCriteria().list(max: getLimitPage(), offset: getCurrentPage()){
```suggestion
        PagedResultList payerList =  Payer.createCriteria().list(max: getLimitPage(), offset: getCurrentPage()) {
```
Sempre deixe um espaço em branco antes de uma chave.

2022-05-26 11:20 UTC, bmorais21 commented on grails-app/services/com/desafio/domain/payment/PaymentService.groovy
> +    public Payment save(Map params) {
Ao invés de receber um Map, é mais interessante deixar claro quais são os parâmetros esperados para salvar Payment, como `value`, `method`, `dueDate`, etc.

Obs: `status` por exemplo, não é necessário receber, pois sempre ela irá começar como `PENDING`

2022-05-26 12:55 UTC, ThiagoKienbaum commented on grails-app/controllers/com/desafio/domain/PaymentController.groovy
> +            render([success: false, message: message(code: 'unknow.error')] as JSON)
```suggestion
            render([success: false, message: message(code: "unknow.error")] as JSON)
```
Por padrão utilize sempre aspas duplas, simples apenas quando necessário

2022-05-26 12:55 UTC, ThiagoKienbaum commented on grails-app/controllers/com/desafio/domain/PaymentController.groovy
> +    def index() {
```suggestion
    def index() {
```

2022-05-26 12:55 UTC, ThiagoKienbaum commented on grails-app/views/payment/create.gsp
> +                data-url="${ g.createLink(controller: 'payment', action: 'save') }">
```suggestion
            <form data-redirect="${g.createLink([controller: 'payment', action: 'index', params: [id: customerId]])}"
                data-url="${g.createLink(controller: 'payment', action: 'save')}">
```
Nestes casos não precisa do espaçamento

2022-05-26 12:55 UTC, ThiagoKienbaum commented on grails-app/controllers/com/desafio/domain/PaymentController.groovy
> +        }
Lá na PayerController vc repetiu esse código, não vale a pena criar uma NamedCriteria para reaproveitar esses filtrosm como esse de customer por exemplo?

2022-05-26 12:55 UTC, ThiagoKienbaum commented on grails-app/domain/com/desafio/domain/payment/Payment.groovy
> +}
Por padrão deixar uma linha em branco no final do arquivo

2022-05-26 12:55 UTC, ThiagoKienbaum commented on grails-app/i18n/messages.properties
> +PaymentStatus.OVERDUE=Vencido
Por padrão deixar uma linha em branco no final do arquivo

2022-05-26 12:55 UTC, ThiagoKienbaum commented on grails-app/services/com/desafio/domain/payment/PaymentService.groovy
> +import grails.gorm.transactions.Transactional
```suggestion
import grails.gorm.transactions.Transactional 
```

2022-05-26 12:55 UTC, ThiagoKienbaum commented on grails-app/services/com/desafio/domain/payment/PaymentService.groovy
> +    public Payment save(Map params) {
Talvez um validateSave até, pq qualquer coisa que não vier no formato esperado, ou não for informado aí vai estourar erro

2022-05-26 12:55 UTC, ThiagoKienbaum commented on grails-app/utils/DateUtils.groovy
> +}
Por padrão deixar uma linha em branco no final do arquivo, validar outros arquivos

2022-05-26 12:55 UTC, ThiagoKienbaum commented on grails-app/views/payment/create.gsp
> +        <title>Nova cobrança</title>
```suggestion
        <meta name="layout" content="main"/>
        <g:set var="entityName" value="${message(code: 'payment.label', default: 'Payment')}"/>
        <title><g:message code="default.create.label" args="[entityName]"/></title>
        <asset:javascript src="application.js"/>
        <asset:javascript src="payment.js"/>
        <title>Nova cobrança</title>
```
Tente sempre manter um padrão de espaçamento no seu código, ali acima vc não estava usando espaço antes de fechar a tag, validar outros arquivos

2022-05-26 12:56 UTC, ThiagoKienbaum requested changes

2022-05-26 12:56 UTC, ThiagoKienbaum commented on grails-app/utils/DateUtils.groovy
> +}
Por padrão deixar uma linha em branco no final do arquivo, validar outros arquivos

2022-06-02 13:19 UTC, ThiagoKienbaum commented
https://github.com/Mikael-Asaas/Asaas/pull/12#discussion_r882632425

Esse comentário foi marcado como resolvido, mas o código não mudou, certo? Sempre que acreditar que um comentário não é pertinente e não deve gerar alterações responde nele para que todos possam acompanhar a motivação.

2022-06-02 13:26 UTC, ThiagoKienbaum requested changes

2022-06-02 13:26 UTC, ThiagoKienbaum commented on grails-app/services/com/desafio/domain/payment/PaymentService.groovy
> +    public Payment save(Map params) {
Esse aqui tbm foi resolvido mas o código não mudou, mesmo esquema do meu comentário se foi decidido manter assim, responde aqui na thread para que a gente possa acompanhar

2022-06-02 14:03 UTC, Mikael-Asaas commented on grails-app/controllers/com/desafio/domain/PaymentController.groovy
> +        }
por enquanto vamos manter assim, a sugestão está adicionada como melhoria no Jira.

2022-06-07 17:34 UTC, ThiagoKienbaum approved these changes

2022-06-07 17:34 UTC, ThiagoKienbaum commented on grails-app/views/payment/create.gsp
> +        <h2 class="h2">Nova cobrança</h2>
Aqui faltou a identação

2022-06-13 17:34 UTC, welingtonloh requested changes

2022-06-13 17:34 UTC, welingtonloh commented on grails-app/controllers/com/desafio/domain/PayerController.groovy
>          Integer customerId = params.int("id")
Utilizar Long para IDs
Id apenas? parece o mesmo caso que o marlon tinha comentado, aqui precisa ser **customerId**

Long customerId = Long.valueOf(params.**customerId**)

2022-06-13 17:34 UTC, welingtonloh commented on grails-app/controllers/com/desafio/domain/PayerController.groovy
> +            eq("customer", Customer.get(customerId))
```suggestion
            eq("customer.id", customerId) 
```
Dessa maneira também funciona, com a vantagem que você não precisa alocar memória para um objeto inteiro, apenas para o Id dele, ou seja, menos uso de memória.

2022-06-13 17:34 UTC, welingtonloh commented on grails-app/controllers/com/desafio/domain/PaymentController.groovy
> +package com.desafio.domain
Isso foi tratado? nenhum comentário explicando, fica estranho. Sempre documente bem suas decisões

2022-06-13 17:34 UTC, welingtonloh commented on grails-app/controllers/com/desafio/domain/PaymentController.groovy
> +        Long customerId = params.long("id")
Aqui valem os mesmos pontos levantados acima para payerController

2022-06-13 17:34 UTC, welingtonloh commented on grails-app/controllers/com/desafio/domain/PaymentController.groovy
> +        List<Payment> paymentList = Payment.createCriteria().list(max: getLimitPage(), offset: getCurrentPage()) {
Pq na controller acima foi usado pagedResultList e aqui apenas uma lista?
Se vocês usarem pagedResultList, ele tem o .totalCount e ai não precisa ser feito Payment.count() (Note que essa contagem não considera os filtros que você aplicou, ele vai na base e conta tudo que existe na base, não é o correto.)

2022-06-13 17:34 UTC, welingtonloh commented on grails-app/domain/com/desafio/domain/payment/Payment.groovy
> -    String description
Ué, o que aconteceu?

2022-06-13 17:34 UTC, welingtonloh commented on grails-app/i18n/messages.properties
> +PaymentMethod.CARD=Cartão de crédito
Ao invés de PaymentMethod vamos padronizar como billingType

2022-06-13 17:34 UTC, welingtonloh commented on grails-app/services/com/desafio/domain/payment/PaymentService.groovy
> +        payment.method = PaymentMethod.valueOf(params.method)
Ao invés de PaymentMethod vamos padronizar como billingType

2022-06-13 17:34 UTC, welingtonloh commented on grails-app/services/com/desafio/domain/payment/PaymentService.groovy
> +        payment.customer = Customer.get(params.long("customerId"))
payment.customer = Customer.get(Long.valueOf(params.customerId))

Vale para Payer.get abaixo isso tbm

2022-06-13 17:34 UTC, welingtonloh commented on grails-app/utils/DateUtils.groovy
> +class DateUtils{
```suggestion
class DateUtils {
```

2022-06-13 17:34 UTC, welingtonloh commented on grails-app/views/payment/create.gsp
> +        <%@ page import="com.desafio.enums.PaymentMethod" %>
Imports sempre no topo, antes da propria tag de html

2022-06-13 17:34 UTC, welingtonloh commented on grails-app/views/payment/create.gsp
> +                <input type="date" name="dueDate" placeholder="Data de vencimento">
Padroniza os placeholders, pq esse começa em maiusculo e acima começa em minusculo?

2022-06-13 17:34 UTC, welingtonloh commented on grails-app/views/payment/create.gsp
> +                    valueMessagePrefix="PaymentMethod"/>
Padronizar como "billingType"

2022-06-13 17:55 UTC, Mikael-Asaas commented on grails-app/controllers/com/desafio/domain/PaymentController.groovy
> +package com.desafio.domain
Tinha conversado com o Yuri que ao mudar o diretório estava dando alguns conflitos e por isso resolvemos manter assim por enquanto.

2022-06-13 21:15 UTC, Mikael-Asaas commented on grails-app/i18n/messages.properties
> +PaymentMethod.CARD=Cartão de crédito
O nome do enum eu vou manter como PaymentMethod porem eu vou definir ela como billingType

2022-06-14 12:18 UTC, marlon407 approved these changes

2022-06-14 12:28 UTC, merged