Payment confirmação de um pagamento pendente
Mikael-Asaas/Asaas pull request #15
Opened 2022-05-24 14:45 UTC by Mikael-Asaas

### Impacto
Essa PR tem como objetivo atualizar uma cobrança pendente (_peiding_) para paga (_paid_).

**Desenvolvido**

- PaymentService add: **confirmedPayment**
- PaymentController add: **confirm**
- _list add: **g:link confirmação de pagamento**

### PR Predecessora
https://github.com/Mikael-Asaas/Asaas/pull/14

### Link da tarefa no JIRA / Trello
https://asaasdev.atlassian.net/browse/STAGS-21?atlOrigin=eyJpIjoiZDYzNTY4NWUwYzhiNDJjOWE2ZGQxZTc1OWRkNzA5OGIiLCJwIjoiaiJ9

### Prints do desenvolvimento
![Confirmar uma cobrança que esteja pendente](https://user-images.githubusercontent.com/101341760/170063756-39fc5637-119c-44ce-8c61-880efd866309.gif)

2022-05-24 15:01 UTC, Yuri-Ferrari requested changes

2022-05-26 11:38 UTC, ThiagoKienbaum commented
Na descrição do PR a tradução do pendente tem um typo, o correto seria pending

2022-05-26 11:49 UTC, ThiagoKienbaum requested changes

2022-05-26 11:49 UTC, ThiagoKienbaum commented on grails-app/controllers/com/desafio/domain/PaymentController.groovy
> +        try {
Evite código fora do try catch
```suggestion
        try {
            Long paymentId = params.long("id")
```

2022-05-26 11:49 UTC, ThiagoKienbaum commented on grails-app/services/com/desafio/domain/payment/PaymentService.groovy
> +    public Payment confirmedPayment(Long paymentId) {
Aqui o retorno Payment não está sendo utilizado, certo? Vale mudar pra void, deixa mais explicito que não precisa de retorno

2022-05-26 11:49 UTC, ThiagoKienbaum commented on grails-app/services/com/desafio/domain/payment/PaymentService.groovy
> +        Payment payment = Payment.get(paymentId)
Se o ID passado não for valido, não vai encontrar uma Payment e vai quebrar logo abaixo, precisamos de uma validação que jogue uma exception caso não encontre, recomendaria fazer esse processo já na controller e passar a Payment pronta para a service

2022-05-26 11:49 UTC, ThiagoKienbaum commented on grails-app/views/payment/_list.gsp
> +                    <td>${payment.id}</td>
```suggestion
                <g:each var="payment" in="${paymentList}">
                    <tr>
                        <td>${payment.id}</td>
```
Faltou identação aqui

2022-05-26 12:00 UTC, ThiagoKienbaum requested changes

2022-05-26 12:00 UTC, ThiagoKienbaum commented on grails-app/views/payment/_list.gsp
> +                        <g:link controller="payment" action="confirm" update="divForm" id='${payment.id}'>Confirmar pagamento</g:link>
```suggestion
                        <g:link controller="payment" action="confirm" update="divForm" id="${payment.id}">Confirmar pagamento</g:link>
```
Por padrão utilize sempre aspas duplas, simples apenas quando necessário

2022-05-26 12:02 UTC, ThiagoKienbaum requested changes

2022-05-26 12:02 UTC, ThiagoKienbaum commented on grails-app/controllers/com/desafio/domain/PaymentController.groovy
> +            render([sucess: false, message: message(code: 'unknow.error')] as JSON)
```suggestion
            render([sucess: false, message: message(code: "unknow.error")] as JSON)
```
Por padrão utilize sempre aspas duplas, simples apenas quando necessário

2022-05-26 12:04 UTC, ThiagoKienbaum requested changes

2022-05-26 12:04 UTC, ThiagoKienbaum commented on grails-app/controllers/com/desafio/domain/PaymentController.groovy
> +        catch (Exception exception) {
```suggestion
        } catch (Exception exception) {
```

2022-05-26 18:12 UTC, Mikael-Asaas commented on grails-app/services/com/desafio/domain/payment/PaymentService.groovy
> +        Payment payment = Payment.get(paymentId)
Eu vou tratar essas validações em uma PR com as validações backend

2022-06-13 17:47 UTC, welingtonloh requested changes

2022-06-13 17:47 UTC, welingtonloh commented on grails-app/services/com/desafio/domain/payment/PaymentService.groovy
> +    public Payment confirmedPayment(Long paymentId) {
O que foi feito em relação a esse comentário? precisa documentar as decisões

2022-06-13 21:15 UTC, Mikael-Asaas commented on grails-app/controllers/com/desafio/domain/PaymentController.groovy
> +import com.desafio.enums.PaymentMethod
O nome do enum eu vou manter como PaymentMethod porem eu vou definir ela como billingType

2022-06-13 21:39 UTC, Mikael-Asaas commented on grails-app/controllers/com/desafio/domain/PaymentController.groovy
> +            render([sucess: false, message: message(code: "unknow.error")] as JSON)
arrumei o código para ficar mais claro a leitura

2022-06-13 21:43 UTC, Mikael-Asaas commented on grails-app/services/com/desafio/domain/payment/PaymentService.groovy
> +    public Payment confirmedPayment(Long paymentId) {
Estou utilizando o retorno de payment na controller

2022-06-14 12:27 UTC, marlon407 commented on grails-app/controllers/com/desafio/domain/PaymentController.groovy
> +        return [customerId: customerId, payerList: payerList, totalCount: Payer.count()]
Nunca pode contar todo o payer, sem levar em consideração customer. Avaliar o comentário do @welingtonloh acima

2022-06-14 12:29 UTC, marlon407 commented on grails-app/controllers/com/desafio/domain/PaymentController.groovy
> +        Long paymentId = params.long("paymentId")
coloca dentro do try catch

2022-06-14 12:29 UTC, marlon407 commented on grails-app/controllers/com/desafio/domain/PaymentController.groovy
> +            render([sucess: false, message: message(code: "unknow.error")] as JSON)
Mas ainda não resolveu o problema

2022-06-14 18:59 UTC, welingtonloh commented on grails-app/controllers/com/desafio/domain/PaymentController.groovy
> +            return
```suggestion
                redirect (controller: "payment", action: "index", params: [customerId: payment.customerId])
                return
```

2022-06-14 19:01 UTC, welingtonloh commented on grails-app/services/com/desafio/domain/payment/PaymentService.groovy
> +    public  Payment confirmPayment(Long paymentId) {
```suggestion
    public Payment confirmPayment(Long paymentId) {
```
espaço sobrando

2022-06-14 19:15 UTC, welingtonloh commented on grails-app/services/com/desafio/domain/payment/PaymentService.groovy
> +        payment.status = PaymentStatus.PAID
E esse requisito?
```
4 - Poder confirmar um recebimento
    - Apenas se cobrança estiver pendente
```

Minha sugestão, adiciona um error ao objeto, retorna ele para controller
Na controller valida se ele tem errors, se tiver exibe mensagem indicando o problema
Caso contrário dá mensagem de sucesso e redireciona para a listagem

Para mensagens utilize:
flash.message = "Apropriação de saldo realizada com sucesso."
flash.type = MessageType.SUCCESS

ou 

if (bankDeposit.hasErrors()) {
    flash.message = message(error: bankDeposit.errors.allErrors[0])
    flash.type = MessageType.ERROR
    redirect(action: "create", params: params)
    return
}

2022-06-15 12:25 UTC, Mikael-Asaas commented on grails-app/controllers/com/desafio/domain/PaymentController.groovy
> +    def confirm() {
Confirmado com o Marlon o usuário pode confirmar uma cobrança devido não ter um sistema de confirmação de pagamento automático.

2022-06-17 12:01 UTC, marlon407 commented on grails-app/controllers/com/desafio/domain/PaymentController.groovy
> +            render([sucess: false, message: message(code: "unknow.error")] as JSON)
Revisar esse ponto conforme comentário anteriro. Precisa testar essa exception

2022-06-17 17:18 UTC, welingtonloh requested changes

2022-06-17 17:18 UTC, welingtonloh commented on grails-app/services/com/desafio/domain/payment/PaymentService.groovy
> +        if (payment.status == PaymentStatus.OVERDUE) throw new Exception("Erro ao confirmar recebimento de cobrança")
```suggestion
        if (payment.status != PaymentStatus.PENDING) throw new Exception("Somente podem ser confirmadas cobranças que estejam pendentes de recebimento")
```

2022-06-17 17:18 UTC, welingtonloh commented on grails-app/controllers/com/desafio/domain/PaymentController.groovy
> +            render([sucess: false, message: message(code: "unknow.error")] as JSON)
Aqui https://github.com/Mikael-Asaas/Asaas/pull/15/files#r897232901 comentei sobre o uso do flash.message, pq essa informação foi ignorada?

2022-06-20 13:31 UTC, marlon407 approved these changes

2022-06-20 14:14 UTC, MANO-EH-ELA commented on grails-app/controllers/com/desafio/domain/PaymentController.groovy
> +            flash.message = "Erro ao confirmar cobrança"
Essa alteração será feita posteriormente em outra PR, conforme alinhei com o Marlon.
Pois será uma alteração que abrangerá todo o sistema.

2022-06-20 14:14 UTC, merged