Mecanismo jobs
Mikael-Asaas/Asaas pull request #16
Opened 2022-05-30 14:03 UTC by Mikael-Asaas

### Impacto
O mecanismo jobs é responsável por atualizar o status de uma cobrança para vencida após o termino do prazo estipulado na criação da cobrança 

### PR Predecessora
https://github.com/Mikael-Asaas/Asaas/pull/15

### Link da tarefa no JIRA / Trello
https://asaasdev.atlassian.net/browse/STAGS-23?atlOrigin=eyJpIjoiYTg3ODI5NjkzYTA2NDI4YWI0ODIzNmNlZWNlNTljZTMiLCJwIjoiaiJ9

### Prints do desenvolvimento
![jobs](https://user-images.githubusercontent.com/101341760/171008317-aa4ec7e4-288b-49dc-953a-fbf8361f4394.gif)

2022-06-02 13:31 UTC, ThiagoKienbaum requested changes

2022-06-13 17:52 UTC, welingtonloh requested changes

2022-06-13 17:52 UTC, welingtonloh commented on grails-app/jobs/desafio/OverDueJob.groovy
> +package desafio
É importante observar e organizar em packages as jobs tbm

Um exemplo de como fazemos no Asaas:
package com.asaas.jobs.asaasCard

Todas as jobs relacionadas a cartão Asaas ficam num mesmo package

2022-06-13 17:52 UTC, welingtonloh commented on grails-app/jobs/desafio/OverDueJob.groovy
> +@Transactional
Para jobs não adicione o transactional, apenas para classes que são services

2022-06-13 17:52 UTC, welingtonloh commented on grails-app/services/com/desafio/domain/payment/PaymentService.groovy
> +    public Payment verifyDueDates() {
Esse nome está mentiroso

Ele diz "verificar datas de vencimento"
Mas na verdade ele busca as vencidas e seta elas, muda o status para vencida

Precisa traduzir melhor isso

2022-06-13 17:52 UTC, welingtonloh commented on grails-app/services/com/desafio/domain/payment/PaymentService.groovy
> +        for(Payment payment : paymentList) {
```suggestion
        for (Payment payment : paymentList) {
```

2022-06-13 21:54 UTC, Mikael-Asaas commented on grails-app/jobs/desafio/OverDueJob.groovy
> +@Transactional
removido

2022-06-14 12:33 UTC, marlon407 commented on grails-app/services/com/desafio/domain/payment/PaymentService.groovy
> +    public List<Payment> list(PaymentStatus paymentStatus, Date yesterday) {
Pra que serve um param yesterday?

2022-06-14 19:29 UTC, welingtonloh commented on grails-app/jobs/desafio/OverDueJob.groovy
> +import com.desafio.enums.PaymentStatus
Pode rever e remover esses imports, estão todos sem uso

2022-06-14 19:29 UTC, welingtonloh commented on grails-app/jobs/desafio/OverDueJob.groovy
> +            log.error "Ocorreu um erro"
O que o @marlon407 quis dizer: log.error "Ocorreu um erro ao marcar as cobranças como vencidas [OverDueJob]"

Pensa que futuramente você terá mais jobs rodando num mesmo servidor, você precisa ser detalhista nos logs, para caso aconteça algum problema, você vá direto na causa do erro. Favor ajustar.

2022-06-14 19:29 UTC, welingtonloh commented on grails-app/services/com/desafio/domain/payment/PaymentService.groovy
> +    public List<Payment> list(PaymentStatus paymentStatus, Date yesterday) {
Por que foi marcado como resolvido sem especificar o que será feito?

2022-06-14 19:29 UTC, welingtonloh commented on grails-app/services/com/desafio/domain/payment/PaymentService.groovy
> +    public Payment verifyOverDueDates() {
Bora ajustar o nome desse método para setAsOverdue ou updateToOverdue, deixando bem mais claro o que está acontecendo dentro dele

2022-06-14 19:38 UTC, Mikael-Asaas commented on grails-app/services/com/desafio/domain/payment/PaymentService.groovy
> +    public List<Payment> list(PaymentStatus paymentStatus, Date yesterday) {
@MANO-EH-ELA

2022-06-14 19:39 UTC, Mikael-Asaas commented on grails-app/jobs/desafio/OverDueJob.groovy
> +            log.error "Ocorreu um erro"
@MANO-EH-ELA

2022-06-15 17:27 UTC, Mikael-Asaas commented on grails-app/jobs/desafio/OverDueJob.groovy
> +            log.error "Ocorreu um erro"
resolvido

2022-06-17 12:04 UTC, marlon407 commented on grails-app/services/com/desafio/domain/payment/PaymentService.groovy
> -        if (payment.status = PaymentService.OVERDUE) throw new Exception("Erro ao realizar confirmação de cobrança")
Porque?

2022-06-17 12:04 UTC, marlon407 commented on grails-app/services/com/desafio/domain/payment/PaymentService.groovy
> +    public List<Payment> list(PaymentStatus paymentStatus, Date yesterday) {
@Mikael-Asaas mão marque como resolvido se não foi indicado o que será feito

2022-06-17 12:11 UTC, marlon407 commented on grails-app/services/com/desafio/domain/payment/PaymentService.groovy
> +    public List<Payment> list(PaymentStatus paymentStatus, Date yesterday) {
@MANO-EH-ELA um param com nome yesterday não tem sentido. Se for passado uma data com o valor de amanhã, ou semana que vem?

2022-06-17 12:13 UTC, Mikael-Asaas commented on grails-app/services/com/desafio/domain/payment/PaymentService.groovy
> -        if (payment.status = PaymentService.OVERDUE) throw new Exception("Erro ao realizar confirmação de cobrança")
Foi corrigido na PR anterior assim que fazer os merge vai trazer as alterações novamente
if (payment.status == PaymentStatus.OVERDUE) throw new Exception("Erro ao confirmar recebimento de cobrança")

2022-06-17 18:08 UTC, Mikael-Asaas commented on grails-app/services/com/desafio/domain/payment/PaymentService.groovy
> +    public List<Payment> list(PaymentStatus paymentStatus, Date yesterday) {
alterado o yesterday para date

2022-06-20 13:32 UTC, welingtonloh commented on grails-app/jobs/desafio/OverDueJob.groovy
> +            log.error "Ocorreu um erro ao marcar as cobranças como vencidas"
```suggestion
            log.error "OverDueJob.execute >> Ocorreu um erro ao marcar as cobranças como vencidas"
```
Fica mais fácil entender qual job está com problema

2022-06-20 13:57 UTC, marlon407 approved these changes

2022-06-20 13:57 UTC, marlon407 commented on grails-app/services/com/desafio/domain/payment/PaymentService.groovy
> +    public List<Payment> list(PaymentStatus paymentStatus, Date date) {
```suggestion
    public List<Payment> list(PaymentStatus paymentStatus, Date dueDate) {
```

2022-06-22 16:58 UTC, marlon407 requested changes

2022-06-22 16:58 UTC, marlon407 commented on grails-app/controllers/com/desafio/domain/PaymentController.groovy
> +        Long customerId = params.long("id")
porque mudou pra id?

2022-06-22 16:58 UTC, marlon407 commented on grails-app/jobs/desafio/OverDueJob.groovy
> +            throw e
pode remover esse throw

2022-06-22 16:58 UTC, marlon407 commented on grails-app/services/com/desafio/domain/payment/PaymentService.groovy
> +    PagedResultList groovyPagedResultList
Não é usado

2022-06-22 16:58 UTC, marlon407 commented on grails-app/utils/DateUtils.groovy
> +    public static Date formatStringToDate(String dueDate, String pattern) {
Deveria permanecer date

2022-06-22 17:12 UTC, MANO-EH-ELA commented on grails-app/services/com/desafio/domain/payment/PaymentService.groovy
> +            le("dueDate", date)
Foi trocado o parâmetro  e o nome do método.
Agora onde era passado date, passa ser dueDate como no restante do fluxo.

2022-06-22 17:12 UTC, MANO-EH-ELA commented on grails-app/controllers/com/desafio/domain/PaymentController.groovy
> +        Long customerId = params.long("id")
ao rodar a aplicação essa linha apresentava erro.
essa troca fez com que a aplicação rodasse sem erros.

2022-06-22 17:13 UTC, MANO-EH-ELA commented on grails-app/jobs/desafio/OverDueJob.groovy
> +            throw e
removido

2022-06-22 17:18 UTC, MANO-EH-ELA commented on grails-app/utils/DateUtils.groovy
> +    public static Date formatStringToDate(String dueDate, String pattern) {
ajustado

2022-06-22 17:21 UTC, marlon407 commented on grails-app/controllers/com/desafio/domain/PaymentController.groovy
> +        Long customerId = params.long("id")
Mas precisa manter o nome do param como customerId, é assim que é passado

2022-06-22 17:21 UTC, marlon407 commented on grails-app/controllers/com/desafio/domain/PaymentController.groovy
> +        Long customerId = params.long("id")
Por exemplo:
https://github.com/Mikael-Asaas/Asaas/pull/16/files#diff-5e74d98def9dda05fce5e4c7fa49f9cbfaaf54e61d391983cd470aeb7130e951R22

2022-06-22 20:19 UTC, marlon407 commented on grails-app/domain/com/desafio/domain/payment/Payment.groovy
> -    PaymentMethod method
Volta esse prop. É necessária para o projeto

2022-06-23 12:28 UTC, MANO-EH-ELA commented on grails-app/domain/com/desafio/domain/payment/Payment.groovy
> -    PaymentMethod method
feito

2022-06-23 14:12 UTC, merged