Att-html-css-js
Mikael-Asaas/Asaas pull request #3
Opened 2022-03-30 12:29 UTC by Mikael-Asaas

Atualizações: HTML, CSS e JavaScript

**Arquivos alterados:** 
- index.gsp
- IndexCss.css
- Viacep.js
- IndexController.js
- Mask.js
- Main.gsp

![Registro](https://user-images.githubusercontent.com/101341760/160833435-cc6b524a-98ed-4bd7-8a7c-cb87dd0f08bb.gif)

**Código desenvolvido:** 
![Codigo](https://user-images.githubusercontent.com/101341760/160834388-e95569a9-66fc-4190-82ff-324b1c83ebc0.gif)

2022-03-31 17:55 UTC, geanfarias commented on build/resources/main/index.gsp
> +    <%-- <link rel="stylesheet" href="style.css" /> --%>
remover comentário

2022-03-31 17:55 UTC, geanfarias commented on build/resources/main/index.gsp
> +    <!-- Titulo do form  -->
https://github.com/Mikael-Asaas/Asaas/pull/3/files#r839879779

2022-03-31 17:56 UTC, geanfarias commented on build/resources/main/index.gsp
> +        <button type="submit" id="send" value="Registrar">Registrar</button>
precisa de value no botão?

2022-03-31 17:56 UTC, geanfarias commented on build/resources/main/layouts/main.gsp
> +    <%-- <asset:stylesheet src="application.css"/> --%>
https://github.com/Mikael-Asaas/Asaas/pull/3/files#r839879779

2022-03-31 17:56 UTC, geanfarias commented on grails-app/assets/javascripts/Index/IndexController.js
> +event.preventDefault();
indentação

2022-03-31 17:57 UTC, geanfarias commented on grails-app/assets/javascripts/Index/Viacep.js
> +"use strict";
qual o sentido do uso do "use strict" e por que faz sentido nesse arquivo?

2022-03-31 17:58 UTC, geanfarias commented on grails-app/assets/javascripts/Index/Viacep.js
> +  const cep = document.getElementById("cep").value.replace("-", "");
dentro de variável prioriza o uso de variáveis do tipo "let", pois depois que a função é executada não será mais preciso usar a variável

2022-03-31 17:58 UTC, geanfarias commented on grails-app/assets/stylesheets/Index/IndexCss.css
> +  /* background-image: url("/image-20210719-140442.png"); */
https://github.com/Mikael-Asaas/Asaas/pull/3/files#r839879779

2022-03-31 18:49 UTC, Mikael-Asaas commented on grails-app/assets/javascripts/Index/Viacep.js
> +"use strict";
Analisando que o projeto atual será um projeto maior de um "Mini Asaas" eu optei por utilizar o modo restrito para prevenir bugs possíveis bugs e também verificando pelo lado de otimização e velocidade de resposta.

2022-04-01 19:46 UTC, geanfarias commented on grails-app/assets/stylesheets/Index/IndexCss.css
> +form button[type="submit"] {
usar classe, evitar aplicar estilo direto no elemento html

2022-04-01 19:49 UTC, geanfarias commented on grails-app/views/index.gsp
> +          <input type="text" name="telefone" id="telefone" placeholder="Telefone" maxlength="15"required/>
```suggestion
          <input type="text" name="telefone" id="telefone" placeholder="Telefone" maxlength="15" required/>
```

2022-04-01 19:50 UTC, geanfarias commented on grails-app/views/index.gsp
> +    <asset:javascript src="Index/Viacep.js" />
a ordem tá certa?

2022-04-01 19:51 UTC, geanfarias commented on grails-app/views/index.gsp
> +    <link rel="shortcut icon" type="image/x-icon" href= "https://www.asaas.com/assets/favicon-14e590c1a04095a343f34c60b0456560.ico"  />
acho interessante baixar e colocar na pasta do projeto

2022-04-01 19:55 UTC, geanfarias commented on grails-app/assets/javascripts/Index/Viacep.js
> +"use strict";
dá uma lida aqui e verifica se ainda faz sentido para seu projeto: https://stackoverflow.com/questions/49387399/use-strict-in-the-middle-of-the-program

2022-04-04 18:52 UTC, marlon407 requested changes
Melhora o nome e descrição do PR, dizendo qual o objetivo e o que esse PR entrega.

2022-04-04 18:52 UTC, marlon407 commented on build/resources/main/index.gsp
> +    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
isso deve ficar no main, que é o gsp que engloba toda nova tela

2022-04-04 18:52 UTC, marlon407 commented on build/resources/main/index.gsp
> +          <input type="text" name="cpf" id="cpf" placeholder="CPF" maxlength="14" required />
teu sistema só termitre PF, não aceita Pessoas Jurídicas?

2022-04-04 18:52 UTC, marlon407 commented on grails-app/assets/javascripts/Index/IndexController.js
> +  return {
Não é melhor serializar o form aqui? Caso um novo campo for adicionado do form, não precisa alterar essa função.
https://stackoverflow.com/questions/11661187/form-serialize-javascript-no-framework

2022-04-04 18:52 UTC, marlon407 commented on grails-app/views/index.gsp
> +    <asset:javascript src="Index/Viacep.js" />
Se a gente usar outro fornecedor de CEP, vamos ter que trocar o nome do arquivo?

2022-04-08 17:55 UTC, geanfarias commented on grails-app/assets/javascripts/Index/IndexController.js
> +const uf = document.getElementById("uf");
algumas variáveis dessas não estão sendo utilizadas

2022-04-11 13:58 UTC, lucasJoseMachado commented on build/stacktrace.log
> +ERROR StackTrace - Full Stack Trace:
da uma atenção para remover coisas como esta no gitignore

2022-04-11 14:00 UTC, lucasJoseMachado commented on grails-app/assets/javascripts/index/BuscaCep.js
> +  return cepPattern = /^[0-9]{8}$/.test(cep);
seria sensato limpar caracteres nao numericos aqui neste método antes de aplicar a validação. Ou o objetivo é dizer q é invalido se conter a formatação de um cep?

2022-04-18 13:32 UTC, merged