Relacionando um customer a um payer
Mikael-Asaas/Asaas pull request #9
Opened 2022-05-16 14:13 UTC by Mikael-Asaas

### Impacto
Todo payer possui um customer, ao editar um customer você terá a opção de adicionar um novo pagador para esse customer.

### PR Predecessora
https://github.com/Mikael-Asaas/Asaas/pull/8

### Link da tarefa no JIRA / Trello
https://asaasdev.atlassian.net/browse/STAGS-12?atlOrigin=eyJpIjoiM2ZjZWUzZTlhYjAyNGUzN2IyNWYxYWFlYjYxYTQxYWQiLCJwIjoiaiJ9

### Prints do desenvolvimento
![Relacionando um customer a um payer](https://user-images.githubusercontent.com/101341760/168612471-9a5b74d7-c3f2-4ab3-ada3-1bef5909943f.gif)

2022-05-16 14:49 UTC, millenadias commented
Em algum momento vai ser exibido uma lista com os pagadores? Me parece que isso é um dos requisitos do projeto, ter a listagem de Payers

2022-05-16 17:05 UTC, geanfarias commented on grails-app/services/com/desafio/domain/payer/PayerService.groovy
> +        Customer customer = Customer.get(params.long("customerId"))
e se não tiver a informação customerId nos params por algum motivo?

2022-05-18 12:48 UTC, millenadias commented on grails-app/controllers/com/desafio/domain/CustomerController.groovy
> +      PagedResultList customerList = Customer.list(max: 10, offset: getCurrentPage())
Usa o getLimitPage da BaseController ao invés de passar o 10 fixo, foi usado esse método em um PR anterior, então creio que da pra usar nesse ai.

2022-05-18 12:48 UTC, millenadias commented on grails-app/domain/com/desafio/domain/payer/Payer.groovy
> +        address size: 2..100, nulllable: false, blank: false
Precisa dessas limitações de tamanho? Não poderia deixar o tamanho padrão que ficaria 255?

2022-05-19 11:50 UTC, Yuri-Ferrari requested changes

2022-05-19 11:50 UTC, Yuri-Ferrari commented on grails-app/views/customer/create.gsp
> +
Remover linha vazia

2022-05-19 12:57 UTC, Yuri-Ferrari approved these changes

2022-05-19 13:12 UTC, merged